### ISSUE TITLE
Update test string in wiki

### ISSUE THREAD

**Issue by jhuber-de** [Thecakeisgit/LocaleKeyboard.js#13]
While I was testing my layout I found out that not every character is tested by the string in the wiki.

This string contains all 95 character from the sample.lang:

!"#$%&'()*+,-./0123456789:;<=>?ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^`_abcdefghijklmnopqrstuvwxyz{|}~ @

EDIT
GitHub is messing around with my string so here is a .txt file containing the string.
[string.txt](https://github.com/Thecakeisgit/LocaleKeyboard.js/files/629611/string.txt)

**Comment by lowlevl** [comment]
Fix :D
