### ISSUE TITLE
Backslash isn't working in de_DE layout

### ISSUE THREAD

**Issue by Nibot1** [Thecakeisgit/LocaleKeyboard.js#14]
If I try to print an backslash my arduino prints an "ß"
Does anybody got an idear ?

**Comment by jhuber-de** [comment]
I will look into it as soon as I get my arduino working again

**Comment by jhuber-de** [comment]
So I got my Arduino working again and all worked fine. I provide you with the .ino file I used for testing and and an .txt file containing the output on my machine. 
[Dckuino.js-4wDj.zip](https://github.com/Thecakeisgit/LocaleKeyboard.js/files/644677/Dckuino.js-4wDj.zip)

**Comment by Nibot1** [comment]
With your Keyboard.h and *.cpp it works.
I don't know what I didi wrong, but OK.
Tank you for fast reply

**Comment by lowlevl** [comment]
Absolutely normal.. The **Keyboard.h** and **Keyboard.cpp** are the fix for the locale..
Fixed #14
