### ISSUE TITLE
Help making a swedish keyboard layout

### ISSUE THREAD

**Issue by 20repsej** [Thecakeisgit/LocaleKeyboard.js#16]
Hello!
I´m trying to make a locale for Swedish keyboard layout but I´m having problem with these keys: \\, ^, ` and ~. I´m very noob at this so a little bit of help should be good.

**Comment by lowlevl** [comment]
Hi ! No problem ;) Can you post a picture of your Keyboard ? and tell me how do you type these 3 keys normally ? :) @20repsej

**Comment by gusgravious** [comment]
Hi there. Just started playing with a digispark and realized I have a problem with the keyboard layout as I also need it to work on Swedish keyboards. I am also a noob :-). I also too need to be able to compile and execute for keyboards on PC and Mac in swedish, meaning 2 slightly different layouts. I found my way here from Seytonics Malduino page (https://malduino.com/converter/info.html).

First of all, the Dckuino.js live version linked to in the instructions is dead (404) and I think it might be a good start if this works. I've found other live version available though I think the link should work anyway.

Second, have I got this right? One should compile using JS, run code through IDE to the device and execute. Characters not working correctly should be modified and cycle repeated. In other words, this is not a "permanent" modification in the IDE that will allow direct coding and compiling in the IDE, you will need to pass through the JS to get the correct key-mapping.

I'd love to contribute though I suppose my lack of knowledge and desperate lack of time might be a problem here. Hopefully there is a JPG attached to this message with 2 keyboards ((mac/pc) suppose some differences are possible moving from stationary to laptop though standard keys should be the same).

![keyboards](https://cloud.githubusercontent.com/assets/26832299/25706704/7a7b4b96-30e1-11e7-9999-af3053e2f9aa.jpg)

Let me know if and how I can help this progress!

// Gus

ADD: So, I hade a few minutes this morning to actually look at what I needed to do. I found your wokrking LIVE version and realized that you actually get the .h and a .cpp file to include when compiling. That is fantastic, big thumbs ut! I'll see what I can manage to accomplish during the weekend. 

One should be able to make a script that prints the hex for all characters in the sample string right?

**Comment by lowlevl** [comment]
Thanks @gusgravious, I'm trying to make an "auto-locale" maker, but do you know how to get the hex code a pressed key ?

**Comment by gusgravious** [comment]
Hi @Nurrl, thanks for replying.

Not yet, I only looked for a coupIe of minutes this morning and found a project where a guy was trying to write a "translator" in C++ that accidentally printed the hex value instead of the key pressed. Somewhere else I found that one could print char variables as hex and dec in C# or something.

I'm not really a programmer and only have limited experience with python and BASH/AWK script though I'll get back to you if I manage to work something out.

**Comment by lowlevl** [comment]
For me I'll go through Python, because we need to take full control of keyboard.. To get the keystrokes ^^

**Comment by gusgravious** [comment]
I did think about Python as well, though I did find this after some quick "phone-googleing"

http://stackoverflow.com/questions/3381614/c-convert-string-to-hexadecimal-and-vice-versa

So this is obviously C++, I have not found a solution in python yet. What if you don't use keyboard input and just iterate through the "test-string", would the HEX output be system dependent (as the locale settings would likely be different?)? Hmmmm, well, I'll stop bugging you with this here and come back if I can muster up a suggestion instead.

**Comment by lowlevl** [comment]
But it's not this hex value we need... The hex values for chars are static... The values we need are the hex keystrokes value :D @gusgravious (Aka. Keyboard raw output values)

**Comment by gusgravious** [comment]
Ouch, that's embarrassing....  Well, it could have been a hole lot worse right, this could have been a public forum, oh wait.... 😰 I'll just put another coin in the ol' noob-jar, hehehe 😄 . I do feel kind of dumb right now though it is quite obvious of course. @Nurrl 

Should I miraculously manage to produce something worth sharing I'll get back to you, otherwise I'll stick to what I know (ctrl+c, ctrl+v) BTW, thank you for keeping your replies civilized, and I did find this site that might useful for comparing mac layouts (https://support.apple.com/en-us/HT201794)

**Comment by lowlevl** [comment]
You're welcome, there is only 3 not working chars, so you might just try to play with the altGrMap ;D
Obviously, this variable store what characters needs to be pushed with AltGr, and it works like this : 
  - `_altGrMap[23] = true;` means "*Use the AltGr modifier for the key index 23 = yes*"
And the key index is the position in the **asciiMap**, from 0 to 127...

**Comment by lowlevl** [comment]
@gusgravious

**Comment by gusgravious** [comment]
@Nurrl No thank you. Yep, this is likely something I can manage, and will solve my issue. If I get around to it I'll try to figure out how to add this to the pile. Meanwhile, I did find this "[showkey](https://linux.die.net/man/1/showkey)", might be interesting and potentially something like this exists in python

**Comment by lowlevl** [comment]
Yep, I knew showkey, but it doesn't output the good hex codes too, I don't know how to make this working .-.

**Comment by lowlevl** [comment]
@loidor Here is the begining of what you want to do :D
