### ISSUE TITLE
The es_ES.lang is totaly invalid and incomplete.

### ISSUE THREAD

**Issue by lowlevl** [Thecakeisgit/LocaleKeyboard.js#2]
We need somebody with a spanish keyboard to fill the file with correct ascii map.

**Comment by d4n5h** [comment]
@Thecakeisgit I'm impressed by you. Good job mate.
You're becoming a great maintainer.

**Comment by d4n5h** [comment]
@Thecakeisgit I don't have a French or a Spanish keyboard. just a regular QWERTY.
So i can't help you with that one.
Sorry.

**Comment by d4n5h** [comment]
@Thecakeisgit By the way, i've referenced this project on my repository if you don't mind.

**Comment by d4n5h** [comment]
@Thecakeisgit http://www.ascii-codes.com/cp852.html Check out this site. it's got Ascii tables for almost all languages.

**Comment by d4n5h** [comment]
@Thecakeisgit https://github.com/NicoHood/HID/issues/22 Check this one out.
It's a good place to ask for help with testing and adding additional layouts.

**Comment by Pedrinbeep** [comment]
@Thecakeisgit I have spanish keyboard. I am very noob but tell what to do.

**Comment by lowlevl** [comment]
Thanks @d4n5h :D i decided to make good maintainement for this and Dckuino.js ;D
@Pedrinbeep I'll tell you tomorrow, i'm really tired, i go to sleep ;D I think i can do it also, i'll just need you to test ^^

**Comment by Pedrinbeep** [comment]
@Thecakeisgit Great! Thank dude!! ;)

**Comment by lowlevl** [comment]
@Pedrinbeep we finally fixed Dckuino.js, so now we just need to update .lang files ;D

**Comment by Pedrinbeep** [comment]
@Thecakeisgit Nice! Tell me what to do for make any test you want on a spanish keyboard, and how to do it please. ;)

**Comment by Pedrinbeep** [comment]
Hi @Thecakeisgit 
I finally try your library with my spanish keyboard and your keyboard.h spanish layout and something ins wrong. The arduino sould write this:

`abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789\\ !#$%&'`*~{}[]()%,;:!?-_./+=<>\"\\`

And it write this:

`abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789ç !·$%/´º(ª^*`+)=%,ñÑ!_'?.-¿¡;:¨ç`

That is all I can help. Thank you.

PS: Do you know if your Dckuino.js can also work with a Teensy? Just for fun.

**Comment by lowlevl** [comment]
Hi @Pedrinbeep, it's been a while :D, Dckuino.js work with teensy, but the layout is messed up and you can't use the modfied Keyboard.h

**Comment by lowlevl** [comment]
@Pedrinbeep For the layout, you made the keys, it's cool, i'll see if i can do something ;D (Do u have a picture of ur keyboard ? xD)

**Comment by Pedrinbeep** [comment]
Hi @Thecakeisgit ! Perfect, I will also try it on Teensy with their own keyboard. 

About my layout keyboard, all yours! Hahaha. Thank you so much.

![photo51816457305173602](https://cloud.githubusercontent.com/assets/23044551/20500791/3a2aec34-b037-11e6-853d-93e1024bfc21.jpg)

**Comment by Borja-Garduno** [comment]
@Thecakeisgit it´s been a while since the last comment, however I just find this git topic. I´m Spanish so my keyboard layout was also mess up. I have I think achieve almost every key (by mixing some of the langs and trying it out), but I´m not capable of printing neither of: | @ # ^.

My Keyboard.cpp looks like:

```c
/*
  Keyboard.cpp

  Copyright (c) 2015, Arduino LLC
  Original code (pre-library): Copyright (c) 2011, Peter Barrett

  This library is free software; you can redistribute it and/or
  modify it under the terms of the GNU Lesser General Public
  License as published by the Free Software Foundation; either
  version 2.1 of the License, or (at your option) any later version.

  This library is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
  Lesser General Public License for more details.

  You should have received a copy of the GNU Lesser General Public
  License along with this library; if not, write to the Free Software
  Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
*/

#include "Keyboard.h"

#if defined(_USING_HID)

//================================================================================
//================================================================================
//  Keyboard

static const uint8_t _hidReportDescriptor[] PROGMEM = {

  //  Keyboard
    0x05, 0x01,                    // USAGE_PAGE (Generic Desktop)  // 47
    0x09, 0x06,                    // USAGE (Keyboard)
    0xa1, 0x01,                    // COLLECTION (Application)
    0x85, 0x02,                    //   REPORT_ID (2)
    0x05, 0x07,                    //   USAGE_PAGE (Keyboard)

  0x19, 0xe0,                    //   USAGE_MINIMUM (Keyboard LeftControl)
    0x29, 0xe7,                    //   USAGE_MAXIMUM (Keyboard Right GUI)
    0x15, 0x00,                    //   LOGICAL_MINIMUM (0)
    0x25, 0x01,                    //   LOGICAL_MAXIMUM (1)
    0x75, 0x01,                    //   REPORT_SIZE (1)

  0x95, 0x08,                    //   REPORT_COUNT (8)
    0x81, 0x02,                    //   INPUT (Data,Var,Abs)
    0x95, 0x01,                    //   REPORT_COUNT (1)
    0x75, 0x08,                    //   REPORT_SIZE (8)
    0x81, 0x03,                    //   INPUT (Cnst,Var,Abs)

  0x95, 0x06,                    //   REPORT_COUNT (6)
    0x75, 0x08,                    //   REPORT_SIZE (8)
    0x15, 0x00,                    //   LOGICAL_MINIMUM (0)
    0x25, 0x65,                    //   LOGICAL_MAXIMUM (101)
    0x05, 0x07,                    //   USAGE_PAGE (Keyboard)

  0x19, 0x00,                    //   USAGE_MINIMUM (Reserved (no event indicated))
    0x29, 0x65,                    //   USAGE_MAXIMUM (Keyboard Application)
    0x81, 0x00,                    //   INPUT (Data,Ary,Abs)
    0xc0,                          // END_COLLECTION
};

Keyboard_::Keyboard_(void)
{
  static HIDSubDescriptor node(_hidReportDescriptor, sizeof(_hidReportDescriptor));
  HID().AppendDescriptor(&node);
}

void Keyboard_::begin(void)
{
}

void Keyboard_::end(void)
{
}

void Keyboard_::sendReport(KeyReport* keys)
{
  HID().SendReport(2,keys,sizeof(KeyReport));
}

extern
const uint8_t _asciimap[128] PROGMEM;
/*
 * _asciimap took from Keyboard.cpp,
 * need somebody to test with spansih layout.
 */

#define SHIFT 0x80
const uint8_t _asciimap[128] =
{
  0x00,             // NUL          0
  0x00,             // SOH
  0x00,             // STX
  0x00,             // ETX
  0x00,             // EOT
  0x00,             // ENQ
  0x00,             // ACK
  0x00,             // BEL
  0x2a,      // BS  Backspace
  0x2b,      // TAB  Tab
  0x28,      // LF  Enter           10
  0x00,             // VT
  0x00,             // FF
  0x00,             // CR
  0x00,             // SO
  0x00,             // SI
  0x00,             // DEL
  0x00,             // DC1
  0x00,             // DC2
  0x00,             // DC3
  0x00,             // DC4          20
  0x00,             // NAK
  0x00,             // SYN
  0x00,             // ETB
  0x00,             // CAN
  0x00,             // EM
  0x00,             // SUB
  0x00,             // ESC
  0x00,             // FS
  0x00,             // GS
  0x00,             // RS           30
  0x00,             // US

  0x2c,          //  ' '
  0x1e|SHIFT,    // !
  0x1f|SHIFT,    // "
		0x20|SHIFT,    // #
  0x21|SHIFT,    // $
  0x22|SHIFT,    // %
  0x23|SHIFT,    // &
  0x2d,    // '
  0x25|SHIFT,    // (               40
  0x26|SHIFT,    // )
  0x30|SHIFT,    // *
  0x30,          // +
  0x36,          // ,
  0x38,          // -
  0x37,          // .
  0x24|SHIFT,    // /
  0x27,          // 0
  0x1e,          // 1
  0x1f,          // 2               50
  0x20,          // 3
  0x21,          // 4
  0x22,          // 5
  0x23,          // 6
  0x24,          // 7
  0x25,          // 8
  0x26,          // 9
  0x37|SHIFT,      // :
  0x36|SHIFT,      // ;
  0x64,            // <             60
  0x27|SHIFT,      // =
  0x64|SHIFT,      // > 
  0x2d|SHIFT,      // ?
		0x64|SHIFT,            // @
  0x04|SHIFT,      // A
  0x05|SHIFT,      // B
  0x06|SHIFT,      // C
  0x07|SHIFT,      // D
  0x08|SHIFT,      // E
  0x09|SHIFT,      // F             70
  0x0a|SHIFT,      // G
  0x0b|SHIFT,      // H
  0x0c|SHIFT,      // I
  0x0d|SHIFT,      // J
  0x0e|SHIFT,      // K
  0x0f|SHIFT,      // L
  0x10|SHIFT,      // M
  0x11|SHIFT,      // N
  0x12|SHIFT,      // O
  0x13|SHIFT,      // P             80
  0x14|SHIFT,      // Q
  0x15|SHIFT,      // R
  0x16|SHIFT,      // S
  0x17|SHIFT,      // T
  0x18|SHIFT,      // U
  0x19|SHIFT,      // V
  0x1a|SHIFT,      // W
  0x1b|SHIFT,      // X
  0x1c|SHIFT,      // Y
  0x1d|SHIFT,      // Z             90
  0x2f,          // [
  0x35,          // bslash
  0x30,          // ]
		0x94|SHIFT,          // ^
  0x38|SHIFT,    // _
  0x2e|SHIFT,    // `
  0x04,          // a
  0x05,          // b
  0x06,          // c
  0x07,          // d               100
  0x08,          // e
  0x09,          // f
  0x0a,          // g
  0x0b,          // h
  0x0c,          // i
  0x0d,          // j
  0x0e,          // k
  0x0f,          // l
  0x10,          // m
  0x11,          // n               110
  0x12,          // o
  0x13,          // p
  0x14,          // q
  0x15,          // r
  0x16,          // s
  0x17,          // t
  0x18,          // u
  0x19,          // v
  0x1a,          // w
  0x1b,          // x               120
  0x1c,          // y
  0x1d,          // z
  0x34,    // {
		0x38|SHIFT,   // |
  0x32,    // }
  0x21,    // ~
  0        // DEL                   127
};

// Init var         
bool _altGrMap[128];
bool _altFine = false;

// Individually define all needed char
void initAltGr() {
  _altFine = true;

  _altGrMap[126] = true; // ~
  _altGrMap[123] = true; // {
  _altGrMap[91] = true;  // [
  _altGrMap[93] = true;  // ]
  _altGrMap[125] = true; // }
  _altGrMap[92] = true;  // bslash
  _altGrMap[124] = true; // |
  _altGrMap[64] = true;  // @
  _altGrMap[35] = true; // #
  _altGrMap[94] = true; // ^
  _altGrMap[96] = true; // `
 }

uint8_t USBPutChar(uint8_t c);

// press() adds the specified key (printing, non-printing, or modifier)
// to the persistent key report and sends the report.  Because of the way
// USB HID works, the host acts like the key remains pressed until we
// call release(), releaseAll(), or otherwise clear the report and resend.
size_t Keyboard_::press(uint8_t k)
{
  uint8_t i;
  if (k >= 136) {      // it's a non-printing key (not a modifier)
    k = k - 136;
  } else if (k >= 128) {  // it's a modifier key
    _keyReport.modifiers |= (1<<(k-128));
    k = 0;
  } else {        // it's a printing key
    int oldKey = k;
    k = pgm_read_byte(_asciimap + k);
    if (!k) {
      setWriteError();
      return 0;
    }
    if (k & 0x80) {            // it's a capital letter or other character reached with shift
      _keyReport.modifiers |= 0x02;  // the left shift modifier
      k &= 0x7F;
    }

    if (!_altFine)
      initAltGr();
    if (_altGrMap[oldKey])
      _keyReport.modifiers |= 0x40;
  }

  // Add k to the key report only if it's not already present
  // and if there is an empty slot.
  if (_keyReport.keys[0] != k && _keyReport.keys[1] != k &&
    _keyReport.keys[2] != k && _keyReport.keys[3] != k &&
    _keyReport.keys[4] != k && _keyReport.keys[5] != k) {

    for (i=0; i<6; i++) {
      if (_keyReport.keys[i] == 0x00) {
        _keyReport.keys[i] = k;
        break;
      }
    }
    if (i == 6) {
      setWriteError();
      return 0;
    }
  }
  sendReport(&_keyReport);
  return 1;
}

// release() takes the specified key out of the persistent key report and
// sends the report.  This tells the OS the key is no longer pressed and that
// it shouldn't be repeated any more.
size_t Keyboard_::release(uint8_t k)
{
  uint8_t i;
  if (k >= 136) {      // it's a non-printing key (not a modifier)
    k = k - 136;
  } else if (k >= 128) {  // it's a modifier key
    _keyReport.modifiers &= ~(1<<(k-128));
    k = 0;
  } else {        // it's a printing key
    int oldKey = k;
    k = pgm_read_byte(_asciimap + k);
    if (!k) {
      return 0;
    }
    if (k & 0x80) {              // it's a capital letter or other character reached with shift
      _keyReport.modifiers &= ~(0x02);  // the left shift modifier
      k &= 0x7F;
    }

    if (_altGrMap[oldKey])
      _keyReport.modifiers &= ~(0x40);
  }

  // Test the key report to see if k is present.  Clear it if it exists.
  // Check all positions in case the key is present more than once (which it shouldn't be)
  for (i=0; i<6; i++) {
    if (0 != k && _keyReport.keys[i] == k) {
      _keyReport.keys[i] = 0x00;
    }
  }

  sendReport(&_keyReport);
  return 1;
}

void Keyboard_::releaseAll(void)
{
  _keyReport.keys[0] = 0;
  _keyReport.keys[1] = 0;
  _keyReport.keys[2] = 0;
  _keyReport.keys[3] = 0;
  _keyReport.keys[4] = 0;
  _keyReport.keys[5] = 0;
  _keyReport.modifiers = 0;
  sendReport(&_keyReport);
}

size_t Keyboard_::write(uint8_t c)
{
  uint8_t p = press(c);  // Keydown
  release(c);            // Keyup
  return p;              // just return the result of press() since release() almost always returns 1
}

Keyboard_ Keyboard;

#endif
```

Any ideas?

**Comment by lowlevl** [comment]
Hi, :D I'm happy too see that you were working on this project :) 
I'm pretty sure that you problem is this that you use <code>|SHIFT</code> on these 4 not working keys ^^
You can't use SHIFT **and** ALTGR at the same time ;D

*NOTE: Keep in mind that ATmega32U4 is purely emulating a Keyboard, so to do #, |, @ and ^, you need to ALTGR + \<key\>, **not** ALTGR + SHIFT + \<key\> :)*

**Comment by lowlevl** [comment]
@Borja-Garduno If you want to you can make a pull request to add your work to the project, it would be great ;D 
Help yourself with -> [Wiki : How to create a locale ?!](https://github.com/Thecakeisgit/LocaleKeyboard.js/wiki/How-to-create-a-locale-%3F!)

**Comment by Borja-Garduno** [comment]
@Thecakeisgit So, which #define should I need for ALTGR? I can see in Keyboard.h the following ones:
#define KEY_LEFT_CTRL   0x80
#define KEY_LEFT_SHIFT    0x81
#define KEY_LEFT_ALT    0x82
#define KEY_LEFT_GUI    0x83
#define KEY_RIGHT_CTRL    0x84
#define KEY_RIGHT_SHIFT   0x85
#define KEY_RIGHT_ALT   0x86
#define KEY_RIGHT_GUI   0x87

However in Keyboard.cpp 0x80 is already used by the Shift key, which is KEY_LEFT_CTRL from above. Which 0xYY should it be?

**Comment by Borja-Garduno** [comment]
Ok, I have realised that I did not need to put anything on the code (for example 0x1e|ALT_GR, // | ). 
#, @ and | now works. I guess it works due to the _altGrMap[n] from below, though I do not completely understand it. I mean, both 0x1e,   // | and 0x1e,  // 1 have the same code. How does it differentiate them?

Also, I´m still stuck with ^and `, which in the Spanish Keyboard is in the same key, as you can see in @Pedrinbeep picture. 

I try this, without success:
0x2f,     // [
0x2f,     // ^
0x2f,    // `

Following the same idea from above I thought it might work. 
^, however, need shift + key + space. Any ideas?
Sorry for bothering you :)

**Comment by lowlevl** [comment]
Hi again @Borja-Garduno : 
  - Yes, you don't need to add any **ALTGR** in the code, because i don't implemented AltGR this way... It's a bit technical and the **_altGrMap** is a var i totally added myself.. It can't be implemented like Shift because **SHIFT** works with bit wise operations, and in **uint8_t** we have only **256**(0-255) possibilities.. So when you add <code>|SHIFT</code>, it means : "Add 0x80 bit to the total." and **0x80(hex) => 128(dec) => 10000000** and when the code checks for <code>|SHIFT</code>, it search for this bold bit : **1**0000000. So if i wanted to add <code>|ALTGR</code>i needed to `#define ALTGR 0x100` (Which is the next bit, but this bit doesn't exists in 8bit.)

  - For `0x1e, // |` and `0x1e, // 1`, the trick is in the **_altGrMap**. When you type **1**, you hit the **1** key, but when you type **|**, you hold AltGr and you hit the **1** key. So your Arduino does the same :D

  - Then for **^** and **\`** when you want to type **^** you hold Shift key and you hit **\`**, so your code might be like this : 
```c
0x2f, // [ <-- For this you defined the _altGrMap
0x2f|SHIFT, // ^ <-- For this you do SHIFT + `
0x2f, // ` <-- For this you just hit `
```

Hope this helps you ;D

**Comment by Borja-Garduno** [comment]
@Thecakeisgit Well, I just tried what you advised, and it isn´t working. I guess that in GB keyboard it is difference. In the Spanish layout, we need to push SHIFT + key + SPACE. It is when space is pressed that the characters appear. Also, the _altGrMap (I guess) won´t work as the correct characters doesn´t appear.

Any ideas how to hit space in the arduino? As soon I achieve this two keys, I will make a pull request (if I guess how to do it :P ).
Thanks for your help so far.

**Comment by lowlevl** [comment]
Yes, we need to make an **_spaceMap** I guess ;D @Borja-Garduno  
(For the pull request refer to the wiki :D)

**Comment by Borja-Garduno** [comment]
@Thecakeisgit Would we need to create a new function for this, or it would be included in initAltGr?
  _spaceMap[255] = true; // ESPACIO
Like this?
I will try to make now the pull request, with the updates so far.

**Comment by lowlevl** [comment]
Yes (we need to create a function and initialize the var) and to work we need to modify the code who is called when typing something ^^ @Borja-Garduno
