### ISSUE TITLE
How to install this?

### ISSUE THREAD

**Issue by DiegoSepu95** [Thecakeisgit/LocaleKeyboard.js#24]
I want to install this into my Arduino app in mac, so i can upload a payload into a badusb ATMEGA32U4 with spanish keyboard layout.

**Comment by lowlevl** [comment]
Hi @DiegoSepu95, sorry for the late answer, for now, it can't be installed in Arduino IDE.. It could be a great update..
For now to use it, you could use [Dckuino.js Live](https://nurrl.github.io/Dckuino.js/), to generate the code, then you could use **Download Sketch** button and select your language.

Seeya :D

**Comment by lowlevl** [comment]
Can I close the issue ? ;D @DiegoSepu95

**Comment by lowlevl** [comment]
Assumed to be solved
