### ISSUE TITLE
Spanish-ISO keyboard layout Problem!

### ISSUE THREAD

**Issue by DiegoSepu95** [Thecakeisgit/LocaleKeyboard.js#26]
I have the Arduino Leonardo (atmega32u4) when this runs, it does not print these characters ~ < > \ .
I tried changing hex codes on the keyboard.cpp but it did not solve the issue.

**Comment by lowlevl** [comment]
Please don't open issues like that .-. Just reply to the one opened...

**Comment by lowlevl** [comment]
Whoops x) I did'nt really read !
Sorry, okay we'll help you xD
@DiegoSepu95

**Comment by DiegoSepu95** [comment]
Solved. @Nurrl 
Here is the [Keyboard.cpp](https://github.com/Nurrl/LocaleKeyboard.js/files/913871/Keyboard.cpp.txt) for the ones with the same problem. 
Just change the extension back to .cpp (because is on .txt) and replace it.
