### ISSUE TITLE
German Keyboard Bug

### ISSUE THREAD

**Issue by ConTRoniiX** [Thecakeisgit/LocaleKeyboard.js#36]
Hello,
there's a bug the german keyboard. If I want to let it type a backslash(\) it types a & instead.
pls fix xD

ConTRoniiX

**Comment by lowlevl** [comment]
Hi,
How do you type this ?

**Comment by ConTRoniiX** [comment]
If I want to type a backslash, I would do this:
```
    delay(defaultDelay);
    Keyboard.print("  \\");
    
    /* ----- End-Script -----*/
    
    Keyboard.end();
  }
}

void loop(){
  ledOn = !ledOn;
  digitalWrite(ledPin, ledOn);
  delay(blinkInterval);
}```

**Comment by ConTRoniiX** [comment]
Kinda messed up the code thingy.

**Comment by lowlevl** [comment]
When I said how, I meant on your keyboard :3

**Comment by ConTRoniiX** [comment]
oh :D i press ALT GR and then the ß

**Comment by ConTRoniiX** [comment]
Hello? Is it fixable?

**Comment by lowlevl** [comment]
Maybe, but as I did for French, I tested manually.. And it was painful .-. @ConTRoniiX

**Comment by ConTRoniiX** [comment]
Well I am sorry for that^^ I opened a new Issue with other Bugs I found, let me know how I can help you
