### ISSUE TITLE
The charaecter - is typing §

### ISSUE THREAD

**Issue by KevinDenys** [Thecakeisgit/LocaleKeyboard.js#7]
fr_FR

powershell.exe -Command \"Start-Process cmd -Verb RunAs\"

turns into

powershell.exe §Command "Start§Process cmd §Verb RunAs"

**Comment by KevinDenys** [comment]
abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789 =#$%&'µ@{[()%,;:=?§!./_-<>"

this is my string output

**Comment by KevinDenys** [comment]
be_BE
http://pastebin.com/qYedLpy7

Now it works changed values and the String is now complete for a belgian dot keyboard

**Comment by lowlevl** [comment]
@KevinDenys Can i close the issue ? ^^

**Comment by KevinDenys** [comment]
I cant get the backslash working :(
